### ISSUE TITLE
Build error: "daemon.go:20: cannot use d"

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-docker-driver#4]
Tried to install on RHEL clone, got this:

```
# go get -u github.com/solidfire/solidfire-docker-driver

# github.com/solidfire/solidfire-docker-driver/daemon
src/github.com/solidfire/solidfire-docker-driver/daemon/daemon.go:20: cannot use d (type SolidFireDriver) as type volume.Driver in argument to volume.NewHandler:
        SolidFireDriver does not implement volume.Driver (wrong type for Mount method)
                have Mount(volume.Request) volume.Response

# go version
go version go1.7 linux/amd64

# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)
```

**Comment by j-griffith** [comment]
Thanks for logging this, Docker changed the request types in Mount and Unmount.  I've pushed a temporary branch with a fix until I have some time to verify a way to do this to keep compatibility, or to just cut releases for the various docker versions.

Let me know if you have any other issues with it.

Thanks!!
https://github.com/solidfire/solidfire-docker-driver/tree/112_support
