### ISSUE TITLE
Switch to GB units or introduce a bin/dec base option?

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-docker-driver#7]
`-o size=1` creates a 1GiB volume which in SolidFire UI translates to 1.1 GB. 

```
PS C:\Program Files\SolidFire> Get-SFVolume -VolumeID 67

VolumeID           : 67
Name               : testsize
AccountID          : 14
CreateTime         : 2016-09-03T09:29:28Z
Status             : active
Access             : readWrite
Enable512e         : False
Iqn                : iqn.2010-01.com.solidfire:nsys.testsize.67
ScsiEUIDeviceID    : 6e73797300000043f47acc0100000000
ScsiNAADeviceID    : 6f47acc1000000006e73797300000043
Qos                : SolidFire.Element.Api.VolumeQOS
VolumeAccessGroups : {}
VolumePairs        : {}
DeleteTime         :
PurgeTime          :
SliceCount         : 1
TotalSize          : 1073741824
BlockSize          : 4096
VirtualVolumeID    :
Attributes         : {platform}
```

According to https://docs.docker.com/engine/reference/commandline/volume_create/ , MB/GB units seem the norm and as importantly the same goes for the SolidFire UI.

In the source code (https://github.com/solidfire/solidfire-docker-driver/blob/master/sfcli/volume.go#L36, if that's what I'm supposed to be checking) that's seems a bit strange (`-o size=1` should be 1 byte, no? and `-o size=1GiB` doesn't work).

It would be better to switch to GB as the default, or maybe - if GiB is retained as the default - add an option to use GB.

**Comment by j-griffith** [comment]
Switched default as per previous issue in commit:  2a0c0c3d47ebf59b1ad66abc458275b20347821e
