### ISSUE TITLE
Issues with volume size option

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-docker-driver#8]
- In SolidFire API, `CreateVolume` takes `totalSize` in byte units and rounds that to the nearest MB unit. Here 1 GiB (1.1. GB)  is the minimum which is slightly different from that. It would be nice if Xm (X MB) was possible to get consistent behavior with the UI and API.
- There's something wrong (I can't figure out what so I won't be specific) with high size values as well. 
  - For example, sometimes it's possible to set volume size to say 9000 GiB, but not always (see below). 
  - Another problem is that even when no error is returned, such volume isn't actually created. I can't tell whether some errors returned by the API aren't caught or it's the API's fault.

```
#  docker volume create -d solidfire --name=testsiz1gib -o type=Bronze -o size=9000
testsiz1gib
#  docker volume create -d solidfire --name=testsiz2gib -o type=Bronze -o size=8900
Error response from daemon: create testsiz2gib: VolumeDriver.Create: Received error response from API request
#  docker volume create -d solidfire --name=testsiz2gib -o type=Bronze -o size=9000
Error response from daemon: create testsiz2gib: VolumeDriver.Create: Received error response from API request
# docker volume create -d solidfire --name=testsiz1gib -o type=Bronze -o size=9000
testsiz1gib
```

**Comment by j-griffith** [comment]
Updated to use units.GB instead of GiB in commit 2a0c0c3d47ebf59b1ad66abc458275b20347821e
